### ISSUE TITLE
Some methods require a PUT instead of POST

### ISSUE THREAD

**Issue by tbowmo** [jens-maus/node-unifi#21]
By looking through the code, the methods for updating settings in unifi, is hardwired to use POST method.

However, I have recently found out that unifi uses a PUT method, when updating things like user groups, (editUserGroup)

It should be configurable to be able to use the correct HTTP method to post / update / delete, regardless, even if json is supplied.

**Comment by jens-maus** [comment]
Instead of forcing developers to specify the request method (POST, PUT, etc.) themselves the API of node-unifi should decide itself which one to take according to the specification. Thus, if some methods/functions are not working as expected please show the output here and discuss which one requires a change in your opinion. Until then I will close this ticket accordingly.
